version: 2.1

commands:
  git:
    description: install git and checkout
    steps:
      - run: |
          apt-get update -q
          apt-get install -q -y git
      - checkout
      - run: git submodule update --init

  install:
    description: install the compiler
    parameters:
      packages:
        type: string
    steps:
      - run: |
          apt-get install -q -y build-essential cmake << parameters.packages >>

  compile:
    description: build the project
    parameters:
      target:
        type: string
      outdir:
        type: string
    steps:
      - run: |
          make << parameters.target >>
          cp << parameters.outdir >>/wasp .
          cp << parameters.outdir >>/wasp_unittests .

jobs:
  build-gcc-debug:
    docker:
      - image: debian:buster
    steps:
      - git
      - install:
          packages: gcc g++
      - compile:
          target: gcc-debug
          outdir: out/gcc/Debug
      - run: ./wasp_unittests

  build-clang-debug:
    docker:
      - image: debian:buster
    steps:
      - git
      - install:
          packages: clang
      - compile:
          target: clang-debug
          outdir: out/clang/Debug
      - run: ./wasp_unittests

  build-clang-release:
    docker:
      - image: debian:buster
    steps:
      - git
      - install:
          packages: clang
      - compile:
          target: clang-release
          outdir: out/clang/Release
      - run: ./wasp_unittests

workflows:
  version: 2
  build:
    jobs:
      - build-gcc-debug
      - build-clang-debug
      - build-clang-release
